version: '3.1'
services:
  mysql:
    privileged: true
    build: xdocker/mysql
    container_name: '${NAME}-mysql'
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${NAME}
      - MYSQL_USER=${NAME}
      - MYSQL_PASSWORD=${NAME}
    networks:
      - xdnet
    restart: on-failure

  nginx:
    privileged: true
    build: xdocker/nginx
    container_name: '${NAME}-nginx'
    working_dir: /application
    volumes:
      - .:/application
      - ./xdocker/nginx/nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template
    ports:
      - ${DEFAULT_DOCKER_PORT}
      - 443:443
    networks:
      - xdnet
      - proxy
    external_links:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=${HOST}
      - NGINX_HOST=${HOST}
      - NGINX_PORT=80
      - NAME=${NAME}
    restart: on-failure
    command: /bin/sh -c "envsubst '$${NGINX_HOST},$${NAME}' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  php-fpm:
    privileged: true
    build: xdocker/php-fpm
    container_name: '${NAME}-php-fpm'
    working_dir: /application
    volumes:
      - docker-sync:/application:nocopy
      - ~/.ssh:/root/.ssh
      - ~/.ssh/config:/etc/ssh/ssh_config
    environment:
      - SYMFONY_ENV=dev
      - VIRTUAL_HOST=${HOST}
      - COMPOSER_ALLOW_SUPERUSER=1
    networks:
      - xdnet
    restart: on-failure

  #  redis:
  #      privileged: true
  #      build: xdocker/redis
  #      container_name: "${NAME}-redis"
  #      volumes:
  #          - redis:/data
  #      ports:
  #          - "6379:6379"
  #      networks:
  #          - xdnet
  #  elasticsearch:
  #      privileged: true
  #      build: ./xdocker/elasticsearch
  #      container_name: "${NAME}-elasticsearch"
  #      volumes:
  #          - esdata:/usr/share/elasticsearch/data
  #      environment:
  #          - cluster.name=xdocker-cluster
  #          - bootstrap.memory_lock=true
  #          - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
  #          - "http.host=0.0.0.0"
  #          - "transport.host=127.0.0.1"
  #          - "xpack.security.enabled=false"
  #      ulimits:
  #          memlock:
  #              soft: -1
  #              hard: -1
  #      ports:
  #          - "9200:9200"
  #          - "9300:9300"
  #      networks:
  #          - xdnet

volumes:
  docker-sync:
    external:
      name: '${NAME}-sync'
#    esdata:
#        driver: local
#    redis:
#        driver: local

networks:
  xdnet:
    driver: 'bridge'
  proxy:
    external:
      name: proxy_default
